### ISSUE TITLE
Having issue with the Node JS installation guide

### ISSUE THREAD

**Issue by nickAP02** [openwallet-foundation/credo-ts#1260]
Hi guys, I've been hustling with the Node JS installation guide I've tried to install first on windows I've followed all the steps of the doc but when I have runned the npx -p @aries-framework/node is-indy-installed nothing appears as an error so I continue with the npm install @aries-framework/core @aries-framework/node and then I got npm err while installing the  @aries-framework/node and it finished like this :
Exit code: 1
Command: node-gyp rebuild
Arguments:
Directory: D:\decentralized-id\node_modules\indy-sdk
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@8.4.1
gyp info using node@16.17.1 | win32 | x64
gyp info find Python using Python version 3.7.9 found at "C:\Users\DELL\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\python.exe"
gyp info find VS using VS2019 (16.11.33214.272) found at:
gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community"
gyp info find VS run with --verbose for detailed information
gyp info spawn C:\Users\DELL\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\python.exe
gyp info spawn args [
gyp info spawn args   'D:\\decentralized-id\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-I',
gyp info spawn args   'D:\\decentralized-id\\node_modules\\indy-sdk\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'D:\\decentralized-id\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\DELL\\AppData\\Local\\node-gyp\\Cache\\16.17.1\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\DELL\\AppData\\Local\\node-gyp\\Cache\\16.17.1',
gyp info spawn args   '-Dnode_gyp_dir=D:\\decentralized-id\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\DELL\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\16.17.1\\\\<(target_arch)\\\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=D:\\decentralized-id\\node_modules\\indy-sdk',
gyp info spawn args   '-Dnode_engine=v8',
eur "-m".
  indy.cc
D:\decentralized-id\node_modules\nan\nan.h(60,10): fatal error C1083: Impossible d'ouvrir le fichier include�: 'node.h'�: No such file or directory [D:\decentralized-id\node_modules\indy-sdk\build\indynodejs.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (D:\decentralized-id\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
gyp ERR! System Windows_NT 10.0.22621
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\decentralized-id\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\decentralized-id\node_modules\indy-sdkgyp ERR! node -v v16.17.1
gyp ERR! node-gyp -v v8.4.1

**Comment by TimoGlastra** [comment]
Closing as a lot has changed. If the issue still persists with latest 0.5.0 alphla, node 18/20 and 0.2.0 of the shared components, please open a new issue. Thanks!
