### ISSUE TITLE
Create an InMemoryWallet for test purposes

### ISSUE THREAD

**Issue by TimoGlastra** [openwallet-foundation/credo-ts#1300]
I once started a browser wallet that I think we could base this of. Not sure if libsodium-wrappers is performant, as for tests it's nice to have something that is _faaaaast_. 

https://github.com/TimoGlastra/aries-framework-javascript/blob/feature/browser/packages/browser/src/BrowserWallet.ts

**Comment by genaris** [comment]
That looks amazing, but regarding your concerns about performance, maybe it could be useful in the mid-term (once we fix the ref-napi issue) to use Askar for tests, as it allows to use in-memory storage and provides natively all crypto we need.

**Comment by TimoGlastra** [comment]
Yes if we're able to solve the perf issues I'm all for using Askar

**Comment by TimoGlastra** [comment]
Done done done
