### ISSUE TITLE
error in demo when "yarn faber" command is executed | Cheqd

### ISSUE THREAD

**Issue by ksanjaykumar1** [openwallet-foundation/credo-ts#1447]
There seems to be an error in cheqd library. If not please guide me on how to resolve it. 

![Screenshot from 2023-05-02 15-19-10](https://user-images.githubusercontent.com/72605368/235635821-71131744-a49f-404d-8b2e-e69dbd123a16.png)

**Comment by TimoGlastra** [comment]
There's a PR open that should fix some things: #1439.

Can you try running from that branch and see if it works?

**Comment by ksanjaykumar1** [comment]
I am getting a similar error. 
![Screenshot from 2023-05-02 17-45-35](https://user-images.githubusercontent.com/72605368/235663733-d18bdeea-97b7-4e17-92e8-5d3060a44240.png)

This time it has thrown two additional errors. One was to update the node version to 18, which I did. 
![Screenshot from 2023-05-02 17-43-32](https://user-images.githubusercontent.com/72605368/235664241-98e72174-6e87-4c49-a49a-8cc1b9c3e70f.png)

![Screenshot from 2023-05-02 17-47-43](https://user-images.githubusercontent.com/72605368/235664288-3ab27bde-5222-43d4-aadf-64af674ced82.png)

**Comment by daidoji** [comment]
@TimoGlastra getting a similar but different error on the install.  I don't have libindy installed though, should I have that before running the demo?

[aries-javascript-framework-demo.txt](https://github.com/hyperledger/aries-framework-javascript/files/11499573/aries-javascript-framework-demo.txt)

**Comment by genaris** [comment]
@ksanjaykumar1 please check my answer [here](https://github.com/hyperledger/aries-framework-javascript/issues/1452#issuecomment-1622661873) to confirm if it's related to the same underlying issue.

**Comment by outSH** [comment]
Having similar error on Fedora:

```
  _____           _                   
 |  ___|   __ _  | |__     ___   _ __ 
 | |_     / _` | | '_ \   / _ \ | '__|
 |  _|   | (_| | | |_) | |  __/ | |   
 |_|      \__,_| |_.__/   \___| |_|   
                                      
error Command failed with signal "SIGINT".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Checked on:
- Node v18.18.2 / NPM 10.2.1 / yarn 1.22.19, both `main` branch and resolution fix proposed by @genaris 
- Node v16.14.2 / NPM 8.10.0 / yarn 1.22.17 (only `main` branch)

OS

```
NAME="Fedora Linux"
VERSION="38 (Workstation Edition)"
ID=fedora
VERSION_ID=38
VERSION_CODENAME=""
PLATFORM_ID="platform:f38"
PRETTY_NAME="Fedora Linux 38 (Workstation Edition)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:38"
DEFAULT_HOSTNAME="fedora"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f38/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=38
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=38
SUPPORT_END=2024-05-14
VARIANT="Workstation Edition"
VARIANT_ID=workstation
```

**Comment by TimoGlastra** [comment]
Can you try to re-run with the latest alpha release and 0.2.0 release for shared components. If the issue persists we can reopen!
