### ISSUE TITLE
Getting error which installing dependencies (ffi-napi)

### ISSUE THREAD

**Issue by vikassoul13** [openwallet-foundation/credo-ts#1529]
yarn add @aries-framework/askar@^0.4.0 @hyperledger/aries-askar-nodejs@^0.1.0

yarn add v1.22.19
warning ../../package.json: No license field
info No lockfile found.
[1/4] :mag:  Resolving packages...
warning @aries-framework/askar > @aries-framework/core > @digitalcredentials/jsonld > @digitalcredentials/rdf-canonize > isomorphic-webcrypto > @unimodules/core@7.1.2: replaced by the 'expo' package, learn more: https://blog.expo.dev/whats-new-in-expo-modules-infrastructure-7a7cdda81ebc
warning @aries-framework/askar > @aries-framework/core > @digitalcredentials/jsonld > @digitalcredentials/rdf-canonize > isomorphic-webcrypto > @unimodules/react-native-adapter@6.3.9: replaced by the 'expo' package, learn more: https://blog.expo.dev/whats-new-in-expo-modules-infrastructure-7a7cdda81ebc
[2/4] :truck:  Fetching packages...
[3/4] :link:  Linking dependencies...
warning " > @aries-framework/askar@0.4.0" has unmet peer dependency "@hyperledger/aries-askar-shared@^0.1.0".
warning "@aries-framework/askar > @aries-framework/core > @digitalcredentials/jsonld > @digitalcredentials/rdf-canonize > isomorphic-webcrypto > react-native-securerandom@0.1.1" has unmet peer dependency "react-native@*".
warning "@aries-framework/askar > @aries-framework/core > @digitalcredentials/jsonld > @digitalcredentials/rdf-canonize > isomorphic-webcrypto > expo-random@13.2.0" has unmet peer dependency "expo@*".
[4/4] :hammer:  Building fresh packages...
[3/4] ⡀ ffi-napi
[-/4] ⡀ waiting...
[-/4] ⡀ waiting...
**error /Users/admin/Documents/Askar AFJ/node_modules/ffi-napi: Command failed.**
Exit code: 1
Command: node-gyp-build
Arguments:
Directory: /Users/admin/Documents/Askar AFJ/node_modules/ffi-napi
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@9.4.0
gyp info using node@18.17.0 | darwin | x64
gyp info find Python using Python version 3.9.6 found at "/Users/admin/.pyenv/versions/3.9.6/bin/python3"
gyp info spawn /Users/admin/.pyenv/versions/3.9.6/bin/python3
gyp info spawn args [
gyp info spawn args   '/usr/local/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/admin/Documents/Askar AFJ/node_modules/ffi-napi/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/admin/Library/Caches/node-gyp/18.17.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/admin/Library/Caches/node-gyp/18.17.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/admin/Library/Caches/node-gyp/18.17.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/admin/Documents/Askar AFJ/node_modules/ffi-napi',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CC(target) Release/obj.target/nothing/../node-addon-api/nothing.o
  LIBTOOL-STATIC Release/nothing.a
warning: /Library/Developer/CommandLineTools/usr/bin/libtool: archive library: Release/nothing.a the table of contents is empty (no object file members in the library define global symbols)
  CC(target) Release/obj.target/ffi/deps/libffi/src/prep_cif.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/types.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/raw_api.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/java_raw_api.o
../deps/libffi/src/java_raw_api.c:328:46: warning: 'ffi_java_raw_size' is deprecated [-Wdeprecated-declarations]
  ffi_java_raw *raw = (ffi_java_raw*)alloca (ffi_java_raw_size (cif));
                                             ^
../deps/libffi/config/mac/x64/ffi.h:299:56: note: 'ffi_java_raw_size' has been explicitly marked deprecated here
size_t ffi_java_raw_size (ffi_cif *cif) __attribute__((deprecated));
                                                       ^
../deps/libffi/src/java_raw_api.c:331:3: warning: 'ffi_java_ptrarray_to_raw' is deprecated [-Wdeprecated-declarations]
  ffi_java_ptrarray_to_raw (cif, avalue, raw);
  ^
../deps/libffi/config/mac/x64/ffi.h:295:93: note: 'ffi_java_ptrarray_to_raw' has been explicitly marked deprecated here
void ffi_java_ptrarray_to_raw (ffi_cif *cif, void **args, ffi_java_raw *raw) __attribute__((deprecated));
                                                                                            ^
2 warnings generated.
  CC(target) Release/obj.target/ffi/deps/libffi/src/closures.o
In file included from ../deps/libffi/src/closures.c:524:
../deps/libffi/src/dlmalloc.c:2937:33: warning: arithmetic on a null pointer treated as a cast from integer to pointer is a GNU extension [-Wgnu-null-pointer-arithmetic]
      used = fp - (m->topsize + TOP_FOOT_SIZE);
                                ^~~~~~~~~~~~~
../deps/libffi/src/dlmalloc.c:2193:17: note: expanded from macro 'TOP_FOOT_SIZE'
  (align_offset(chunk2mem(0))+pad_request(sizeof(struct malloc_segment))+MIN_CHUNK_SIZE)
   ~~~~~~~~~~~~~^~~~~~~~~~~~~

**Comment by berendsliedrecht** [comment]
What is your node version?

**Comment by vikassoul13** [comment]
> What is your node version?

node --version                                                               
v18.17.0

**Comment by berendsliedrecht** [comment]
What macOS do you have?

**Comment by vikassoul13** [comment]
> What macOS do you have?

Ventura 13.4.1
intel processor

**Comment by TimoGlastra** [comment]
Closing as a lot has changed. If the issue still persists with latest 0.5.0 alphla, node 18/20 and 0.2.0 of the shared components, please open a new issue. Thanks!
