### ISSUE TITLE
yarn install aries framework javascript

### ISSUE THREAD

**Issue by Mohitv** [openwallet-foundation/credo-ts#1537]
Getting the below error:

yarn install
yarn install v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning "@aries-framework/anoncreds > @aries-framework/core > @digitalcredentials/jsonld-signatures > isomorphic-webcrypto > expo-random@13.1.1" has unmet peer dependency "expo@*".
warning "@aries-framework/anoncreds > @aries-framework/core > @digitalcredentials/jsonld-signatures > isomorphic-webcrypto > react-native-securerandom@0.1.1" has unmet peer dependency "react-native@*".
warning " > @aries-framework/anoncreds-rs@0.4.0" has unmet peer dependency "@hyperledger/anoncreds-shared@^0.1.0".
warning " > @aries-framework/askar@0.4.0" has unmet peer dependency "@hyperledger/aries-askar-shared@^0.1.0".
warning " > @aries-framework/indy-sdk-to-askar-migration@0.4.0" has unmet peer dependency "@hyperledger/aries-askar-shared@^0.1.0".
warning " > @aries-framework/indy-vdr@0.4.0" has unmet peer dependency "@hyperledger/indy-vdr-shared@^0.1.0".
[4/4] Building fresh packages...
[1/7] ⡀ ref-napi
[-/7] ⡀ waiting...
[3/7] ⡀ indy-sdk
[-/7] ⡀ waiting...
error /home/azureuser/hyperledger-afj-040-release-workshop/node_modules/indy-sdk: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments:
Directory: /home/azureuser/hyperledger-afj-040-release-workshop/node_modules/indy-sdk
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@8.4.1
gyp info using node@18.17.0 | linux | x64
gyp info find Python using Python version 3.8.10 found at "/usr/bin/python3"
gyp http GET https://nodejs.org/download/release/v18.17.0/node-v18.17.0-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v18.17.0/node-v18.17.0-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v18.17.0/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v18.17.0/SHASUMS256.txt
gyp info spawn /usr/bin/python3
gyp info spawn args [
gyp info spawn args   '/home/azureuser/hyperledger-afj-040-release-workshop/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/azureuser/hyperledger-afj-040-release-workshop/node_modules/indy-sdk/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/azureuser/hyperledger-afj-040-release-workshop/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/azureuser/.cache/node-gyp/18.17.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/azureuser/.cache/node-gyp/18.17.0',
gyp info spawn args   '-Dnode_gyp_dir=/home/azureuser/hyperledger-afj-040-release-workshop/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/azureuser/.cache/node-gyp/18.17.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/azureuser/hyperledger-afj-040-release-workshop/node_modules/indy-sdk',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp ERR! build error
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/home/azureuser/hyperledger-afj-040-release-workshop/node_modules/which/which.js:10:17)
gyp ERR! stack     at /home/azureuser/hyperledger-afj-040-release-workshop/node_modules/which/which.js:57:18
gyp ERR! stack     at new Promise (<anonymous>)
gyp ERR! stack     at step (/home/azureuser/hyperledger-afj-040-release-workshop/node_modules/which/which.js:54:21)
gyp ERR! stack     at /home/azureuser/hyperledger-afj-040-release-workshop/node_modules/which/which.js:71:22
gyp ERR! stack     at new Promise (<anonymous>)
gyp ERR! stack     at subStep (/home/azureuser/hyperledger-afj-040-release-workshop/node_modules/which/which.js:69:33)
gyp ERR! stack     at /home/azureuser/hyperledger-afj-040-release-workshop/node_modules/which/which.js:80:22
gyp ERR! stack     at /home/azureuser/hyperledger-afj-040-release-workshop/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /home/azureuser/hyperledger-afj-040-release-workshop/node_modules/isexe/mode.js:8:5
gyp ERR! System Linux 5.15.0-1042-azure
gyp ERR! command "/usr/bin/node" "/home/azureuser/hyperledger-afj-040-release-workshop/node_modules/indy-sdk/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /home/azureuser/hyperledger-afj-040-release-workshop/node_modules/indy-sdk

**Comment by Mohitv** [comment]
The same issue seen when trying to install the code from release 04 workshop. The node version is 18

**Comment by berendsliedrecht** [comment]
It seems that you have not installed `make`. Could you install it and try again?

**Comment by Mohitv** [comment]
Thanks @berendsliedrecht I installed make and addressed another issue mentioned in #1520. But when I ran the following command(Ubuntu 20.04) it again gave this error:
yarn alice
yarn run v1.22.19
$ ts-node src/AliceInquirer.ts
/home/azureuser/aries-framework-javascript/node_modules/node-gyp-build/node-gyp-build.js:60
  throw new Error('No native build was found for ' + target + '\n    loaded from: ' + dir + '\n')
        ^
Error: No native build was found for platform=linux arch=x64 runtime=node abi=108 uv=1 libc=glibc node=18.17.0
    loaded from: /home/azureuser/aries-framework-javascript/node_modules/ref-napi

    at Function.load.resolve.load.path (/home/azureuser/aries-framework-javascript/node_modules/node-gyp-build/node-gyp-build.js:60:9)
    at load (/home/azureuser/aries-framework-javascript/node_modules/node-gyp-build/node-gyp-build.js:22:30)
    at Object.<anonymous> (/home/azureuser/aries-framework-javascript/node_modules/ref-napi/lib/ref.js:8:53)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Object.require.extensions.<computed> [as .js] (/home/azureuser/aries-framework-javascript/node_modules/ts-node/src/index.ts:1608:43)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Function.Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:110:18)
error Command failed with exit code 1.

**Comment by TimoGlastra** [comment]
Closing, as there's been quite some changes to the setup. If the issue persists please open a new issue
