### ISSUE TITLE
Dead link in demo docs

### ISSUE THREAD

**Issue by bryce-mcmath** [openwallet-foundation/credo-ts#1577]
In the demo guide, there is a section for platform specific setup. https://github.com/hyperledger/aries-framework-javascript/tree/main/demo#platform-specific-setup

The only link for NodeJS in this section results in essentially a 404 page: 
![page not found](https://github.com/hyperledger/aries-framework-javascript/assets/32586431/f3aa32c1-4b03-4aa0-90c7-413fedf4b944)

**Comment by genaris** [comment]
Thanks for raising this up. I guess it should go to https://aries.js.org/guides/0.4/getting-started/prerequisites. For the moment, when running the demo from this repo we need to install also indy-sdk (even if not used for it), so you'll need to follow https://aries.js.org/guides/0.4/getting-started/set-up/indy-sdk#installing-the-indy-sdk. 

Hopefully we'll fix this setup very soon (@TimoGlastra @berendsliedrecht please go ahead with the new shared component JS wrappers releases 🙏 🥺 😄 )!

**Comment by bryce-mcmath** [comment]
@genaris Not sure if this should be a separate issue or if I've just made a common blunder, but the install is failing even after following the indy-sdk guide.

### Versions:
Mac: Ventura 13.5.2 (Intel)
Homebrew: 4.1.12 
Node: 16.15.1
Yarn: 1.22.19
Make: 4.4.1

Installed libindy with homebrew as per https://aries.js.org/guides/0.4/getting-started/set-up/indy-sdk/macos-intel
Running `npx -p @aries-framework/node@^0.3 is-indy-installed` doesn't error

Error output from `yarn install`: 
```sh
error /Users/bryce/repos/aries-framework-javascript/node_modules/indy-sdk: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: /Users/bryce/repos/aries-framework-javascript/node_modules/indy-sdk
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@8.4.1
gyp info using node@16.15.1 | darwin | x64
gyp info find Python using Python version 3.11.5 found at "/usr/local/opt/python@3.11/bin/python3.11"
gyp info spawn /usr/local/opt/python@3.11/bin/python3.11
gyp info spawn args [
gyp info spawn args   '/Users/bryce/repos/aries-framework-javascript/node_modules/indy-sdk/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/bryce/repos/aries-framework-javascript/node_modules/indy-sdk/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/bryce/repos/aries-framework-javascript/node_modules/indy-sdk/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/bryce/Library/Caches/node-gyp/16.15.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/bryce/Library/Caches/node-gyp/16.15.1',
gyp info spawn args   '-Dnode_gyp_dir=/Users/bryce/repos/aries-framework-javascript/node_modules/indy-sdk/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/bryce/Library/Caches/node-gyp/16.15.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/bryce/repos/aries-framework-javascript/node_modules/indy-sdk',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/indynodejs/src/indy.o
  SOLINK_MODULE(target) Release/indynodejs.node
ld: library not found for -lindy
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/indynodejs.node] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/bryce/repos/aries-framework-javascript/node_modules/indy-sdk/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (node:events:527:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
gyp ERR! System Darwin 22.6.0
gyp ERR! command "/Users/bryce/.nvm/versions/node/v16.15.1/bin/node" "/Users/bryce/repos/aries-framework-javascript/node_modules/indy-sdk/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /Users/bryce/repos/aries-framework-javascript/node_modules/indy-sdk
```

Tried from both the root of the project and from the demo folder, same result.

**Comment by genaris** [comment]
Oh that's sad 😞 . Clearly the key line there is `ld: library not found for -lindy`. @berendsliedrecht any idea what can be the reason for `is-indy-installed` to pass and not being able to find the libindy afterwards?

BTW a few weeks ago I've set up a separated repo extracting the demo (as a colleague of mine had issues as well), so it does not require Indy SDK: https://github.com/genaris/aries-framework-javascript-demo. It's slightly outdated but maybe can help you if you just want to start playing around with AFJ.

**Comment by bryce-mcmath** [comment]
I'll check it out and help if I can! Thank you.

**Comment by genaris** [comment]
I couldn't reproduce neither in my Macbook Pro M1 or in my x86_64 Linux box (even using the same npm and node versions as you), but I'm running into the same issue when attempting to create a Docker image based on `node:lts`. According to them, the problem can be related to the upgrade from npm 9.7.2 to 9.8.1:

- https://github.com/nodejs/node/issues/49737
- https://github.com/npm/cli/issues/6842
