### ISSUE TITLE
Support of a new network

### ISSUE THREAD

**Issue by valavanisleonidas** [openwallet-foundation/credo-ts#1602]
Hello,

I want to work with the quorum network and would like to expand on the current functionality and create the necessary modules for the connection( vdr, dids etc.). I would like some pointers and how easy it could be.

If it works I would be more than happy to contribute with a PR.

**Comment by TimoGlastra** [comment]
Sorry for the late reply. If you want to add a new network you should implement the `DidResolver` ,`DidRegistrar` and `AnonCredsRegistry` (if you want to do anoncreds). You can look at the indy-vdr / cheqd packages for references!
