### ISSUE TITLE
Move indy vdr and cheqd integration to separate vdr repository

### ISSUE THREAD

**Issue by TimoGlastra** [openwallet-foundation/credo-ts#1609]
This will make the development on the main repository a lot simpler as there's no ledgers to set up, and it makes the integration tests a lot easier. With indy-sdk removed we can run all tests fine without testing the ledger integration, and this could then be in a separate repo dedicated to testing the VDR integration of AFJ.

So that would mean `@aries-framework/indy-vdr` and `@aries-framework/cheqd` will be moved

Thoughts?

**Comment by TimoGlastra** [comment]
Started working on an initial test: https://github.com/TimoGlastra/aries-framework-javascript-vdr. Sems quite easy to get it moved over. Thought was to release it under `@aries-framework-vdr/*` (or another name when it's moved to OWF)

**Comment by genaris** [comment]
I think this would certainly help on the CI, but I'm a bit worried about the fact that it will be another repo to maintain that can become out of sync. This has been a source of confusion in the case of REST package for instance (which is still not up to date right now), and it can be problematic considering how important indy-vdr is for most consumers of AFJ nowadays.

In my opinion, we should rethink the test suite in a way that it is not so dependent on the ledger setup, and only run those tests related to ledger within the corresponding packages test suites. All those "E2E tests" we have now for things like mediation and credential issuance/proof request can still be there but using an in-memory AnonCredsRegistry. 

So if we manage to reduce the indy-vdr/cheqd tests to a minimum set, and scoped to their packages, maybe we can improve CI run time significantly and also not force every developer to set up an indy ledger if they are not working on indy-vdr related stuff (i.e. something like we can do with postgres and cheqd, where we ignore the test name pattern and run the other suites).

**Comment by berendsliedrecht** [comment]
My preference is more in the direction of what @genaris is suggesting. I think having heavier dependencies in the repository is not such a bad thing as long as users do not get them when they are not going to use them. Flaky tests are a big issue and extremely annoying, but I'd rather only have tests run if something in their package changed (or something similiar) then to move VDR specific modules to another repository.

But, if the difference in time and effort between moving to another repository and fixing these tests in a way like @genaris suggested, then I have no issue with moving them to another repository.
