### ISSUE TITLE
[Query] Issues regarding json-ld and sd-jwt

### ISSUE THREAD

**Issue by obhi-datta** [openwallet-foundation/credo-ts#1707]
I have two queries.
- Is there sufficient support in Credo for establishing the complete SSI trust triangle with JSON-LD credentials? ( Issuance, Proof, Verification)
- Is the sd-jwt module compatible with the stable release 0.4.2 ? I tried using it with existing stable modules but encountered issues during agent startup.

**Comment by TimoGlastra** [comment]
Hey @obhi-datta, to answer your questions:
- somewhat we have support for jsonld but there's a few caveats, in that it doesn't work particularly well in React Native (requires a lot of hacks) and that you probably want to implement your own document loader as there's no caching really / pre-fetched context
- it's not compatible with 0.4.2, only starting from 0.5.0 (which is yet to be released). Not however that we're merging SD-JWT into core (as part of the openid4vc) and there will be quite some breaking changes before 0.5.0 is released. We do intend to create 0.5.0 release very soon though

Hope this helps

**Comment by obhi-datta** [comment]
Thanks, @TimoGlastra, can we expect the release of 0.5.0 within the first quarter of this year?

**Comment by TimoGlastra** [comment]
> can we expect the release of 0.5.0 within the first quarter of this year?

Yes!
