### ISSUE TITLE
Mediator messages queue

### ISSUE THREAD

**Issue by zdravko61** [openwallet-foundation/credo-ts#1768]
Hey, 

I'm trying to replace mediator's in memory queue with persistent one using the storage service, so posgres db for now, maybe some experiments with redis later.

Im using 0.4.2 version of the framework and my code looks close to this:
```js

  const agent = new Agent({
    config,
    dependencies: agentDependencies,
    modules: {
      askar: new AskarModule({
        ariesAskar,
      }),
      mediator: new MediatorModule({
        autoAcceptMediationRequests: true,
      }),
      connections: new ConnectionsModule({
        autoAcceptConnections: true,
      }),
    },
  });
  
  agent.dependencyManager.registerSingleton(
    InjectionSymbols.MessageRepository,
    MessageQueue,
  );
```

Where Message Queue class is my implementation. takeFromQueue,add,getAvailableMessagesCount are implemented according to MessageRepository interface.

```js

export class MessageQueue implements MessageRepository {
  private messageRepository: DbRepository;
  private agentContext: AgentContext;

  public constructor(
    agentContext: AgentContext,
    messageRepository: DbRepository,
  ) {
    this.messageRepository = messageRepository;
    this.agentContext = agentContext;
  }
  
  takeFromQueue()
  add()
  getAvailableMessagesCount()
  ```

  DbRepo does inject StorageService
  
```js
@injectable()
export class DbRepository extends Repository<MessageRecord> {
  public constructor(
    @inject(InjectionSymbols.StorageService)
    storageService: StorageService<MessageRecord>,
    eventEmitter: EventEmitter,
  ) {
    super(MessageRecord, storageService, eventEmitter);
  }
}
```

The problem is that the add method from MessageQueue is never called. Here are some logs: 

```
DEBUG: Resolving services for connection theirDid did:peer:1zQmbNdLSfQT4GRw7nyZoJZZZfNq69j8SX7gJVnfkHiKGY2E.
DEBUG: resolving didUrl did:peer:1zQmbNdLSfQT4GRw7nyZoJZZZfNq69j8SX7gJVnfkHiKGY2E
DEBUG: Retrieved 0 services for message to connection '1356d8c6-5727-458e-8bf8-e008ea2e3e9e'(689cfa4f-22ff-4ef1-a53a-de4a4b0fbc57)' {
  "hasQueueService": true
}
DEBUG: Queue packed message for connection 1356d8c6-5727-458e-8bf8-e008ea2e3e9e (689cfa4f-22ff-4ef1-a53a-de4a4b0fbc57)
```

The last log is coming from MessageSender and after the debug log, messageRepository add method is called. 
```
    if (queueService) {
      this.logger.debug(`Queue packed message for connection ${connection.id} (${connection.theirLabel})`)
      await this.messageRepository.add(connection.id, encryptedMessage)
      return
    }
```
But the logs from my add method in MessageQueue does not appear. 

Strangely If I turn on my mobile app so it does connect to the mediator I see that getAvailableMessagesCount from MessageQueue is called from V2MessagePickupProtocol and does show the logs from my method. 

if I try to resolve message repository after registration I see that it does resolve properly to my class.

```
  console.log(
    agent.dependencyManager.resolve(InjectionSymbols.MessageRepository),
  );

MessageQueue {
  messageRepository: DbRepository {
    storageService: AskarStorageService {},
    recordClass: [class MessageRecord extends BaseRecord] { type: 'MessageRecord' },
    eventEmitter: EventEmitter { eventEmitter: [EventEmitter], 'stop$': [Subject] }
  },
  agentContext: AgentContext {
    dependencyManager: DependencyManager {
      container: [InternalDependencyContainer],
      registeredModules: [Object]
    },
    contextCorrelationId: 'default'
  }
}
```

Any ideas, what am I doing wrong, why message-pickup module is able to resolve my implementation, but MessageSender is not?

**Comment by TimoGlastra** [comment]
I tbink you need to create a dependency manager first and then pass that to the agent. When you register it afterwards the default in memory message repository is already used in several places.

In 0.5.0 this is now handled through the message pickup api i think and you can configure it in the module config i think. @genaris do you have an example of how that'd look?

**Comment by zdravko61** [comment]
> I tbink you need to create a dependency manager first and then pass that to the agent. When you register it afterwards the default in memory message repository is already used in several places.

Totally solved my problem, I didn't saw that there is a second param for the agent that is the DP. Thanks @TimoGlastra  

Anyway for someone that is looking at this:

```js

  const dp = new DependencyManager();

  dp.registerSingleton(InjectionSymbols.MessageRepository, MessageQueue);

  const agent = new Agent(
    {
      config,
      ....
    },
    dp,
  );
  ```
