### ISSUE TITLE
Migrate record metadata when migrating from AnonCredsCredentialRecord to W3CCredentialRecord

### ISSUE THREAD

**Issue by genaris** [openwallet-foundation/credo-ts#1801]
Please correct me if I'm wrong but as far as I could see/test, if it happened to me to have an AFJ 0.4.2 wallet whose `AnonCredsCredentialRecord` include custom metadata (set by the controller, not the internal ones set by the framework), when upgrading to Credo 0.5.0 I'll lose any custom metadata for them, since the newly generated records do not take it into account.

If this is the case, I think we should fix it because otherwise we'll complicate (or even block) the migration path for existing apps that might have been relying on that feature for their records.

**Comment by TimoGlastra** [comment]
Good catch, yes we should fix that

**Comment by TimoGlastra** [comment]
@auer-martin is going to take a look at this
