### ISSUE TITLE
Failed loading react-native app with IndyVdrModule

### ISSUE THREAD

**Issue by ismapolis** [openwallet-foundation/credo-ts#1820]
After adding and configuring indyVdr to agent modules, react-native app fail to start. It throws this error:
`ERROR  TypeError: Cannot read property 'install' of null, js engine: hermes`
The error trace says it `failed to install the turbomodule: indyVdr.`

I am using credo-ts 0.5.1 and hyperledger 0.2.0 libraries.
For react-native development I use expo 49  and react-native 0.72.10.

**Comment by TimoGlastra** [comment]
Did you add @hyperledger/indy-vdr-react-native to your react native dependencies?

Did you run expo prebuild command afterwards? If on iOS did you run pod install in ios directory?

**Comment by ismapolis** [comment]
Hello, you were right about expo prebuild, thanks.
