### ISSUE TITLE
Cannot find module '@aries-framework/react-native'

### ISSUE THREAD

**Issue by Pratik-1001** [openwallet-foundation/credo-ts#1822]
After running the installation steps I am receiving this error in react-native.
<img width="1512" alt="Screenshot 2024-04-08 at 1 11 21 PM" src="https://github.com/openwallet-foundation/credo-ts/assets/41784693/55943a8a-95a2-408e-8c3e-9e2f14d42c48">

**Comment by TimoGlastra** [comment]
Did you add it to your package.json and ran npm/yarn install?

**Comment by Pratik-1001** [comment]
@TimoGlastra I have followed these instructions 
https://credo.js.org/guides/getting-started/set-up/aries-askar
<img width="486" alt="Screenshot 2024-04-08 at 4 03 25 PM" src="https://github.com/openwallet-foundation/credo-ts/assets/41784693/39e02a8b-509e-4976-8cbc-b417a1e6b58d">

**Comment by TimoGlastra** [comment]
Aries askar is a package you can setup, but you also need to follow general getting started guide: https://credo.js.org/guides/getting-started/set-up

**Comment by Pratik-1001** [comment]
Error is resolved after this step

yarn add @aries-framework/core@^0.4.0 @aries-framework/react-native@^0.4.0 react-native-fs react-native-get-random-values

mentioned in the above link. 
Thanks @TimoGlastra !
