### ISSUE TITLE
What is this domain referring to ? and why to use it ?

### ISSUE THREAD

**Issue by Pratik-1001** [openwallet-foundation/credo-ts#1823]
<img width="735" alt="Screenshot 2024-04-08 at 5 17 13 PM" src="https://github.com/openwallet-foundation/credo-ts/assets/41784693/326343ce-a4e8-4db9-bbda-7a63f1bbfae1">

**Comment by berendsliedrecht** [comment]
The domain can be used so when a user vists the URL, you could choose to render a QR code on that page with the invitation (as long as you own the domain of course). If you do not intend on using it, a sample domain can be used.

For the future, it might be nice to know that we have a Discord (https://discord.com/invite/yjvGPd5FCU) which is a better place for these questions.
