### ISSUE TITLE
Wrong schema Id is stored for credentials

### ISSUE THREAD

**Issue by sairanjit** [openwallet-foundation/credo-ts#1874]
While storing the credential in wallet if the`did` of `schemaId` and `credDefId` are different then the wallet uses the did of `credDefId` for `schemaId`. 

- The issue is here https://github.com/openwallet-foundation/credo-ts/blob/main/packages/indy-vdr/src/anoncreds/IndyVdrAnonCredsRegistry.ts#L274
- Same `namespaceIdentifier` is passed to function `this.fetchIndySchemaWithSeqNo` but it should be of the `schemaId`

From where can we use the same `namespaceIdentifier` for `schemaId` ?

**Comment by TimoGlastra** [comment]
Ah good catch. We should probably add tests where the schema creator is different from the cred def creator.

Would you be able to create a fix, and also add some tests?

**Comment by sairanjit** [comment]
Yeah Sure @TimoGlastra

**Comment by pallavighule** [comment]
@sairanjit @TimoGlastra  I am looking into this . I will raise the PR soon
