### ISSUE TITLE
referent/cred_id generation in Bifold

### ISSUE THREAD

**Issue by Pratik-1001** [openwallet-foundation/credo-ts#1876]
<img width="1503" alt="image" src="https://github.com/openwallet-foundation/credo-ts/assets/41784693/8eda3d03-4d71-4e9f-b826-49adc118a29b">

How to hit this particular function in bifold. Because of this I am not able to generate any cred_id or referent which is required for verification..

**Comment by genaris** [comment]
I guess this is more related to [Bifold](https://github.com/openwallet-foundation/bifold-wallet), so I suggest you to open an issue there. If I'm wrong please feel free to reopen it!
