### ISSUE TITLE
Restoring wallet from local storage in bifold fails

### ISSUE THREAD

**Issue by Arif-Shahriar028** [openwallet-foundation/credo-ts#1936]
I am working on backup and restore wallet functionality in bifold. Backup functionality is working fine with `agent.wallet.export`. But when restoring the wallet by `agent.wallet.import`, I encountered an error:

> Error importing wallet '': Error connecting to database pool
> Caused by: error returned from database: (code: 26) file is not a database

In old version of bifold (v1.0.0-alpha.81), export function creates just one sqlite backup file. But current bifold version (v1.0.0-alpha.256) is creating two backup binary files: fileName-shm and fileName-wal. I am  selecting the -wal file path for importing the wallet. 

 Backup functionality code snippet: 

![image](https://github.com/openwallet-foundation/credo-ts/assets/61360727/d2401b9a-904f-4904-a537-a2a00e0fb4a5)

Created backup files: 
![image](https://github.com/openwallet-foundation/credo-ts/assets/61360727/4000271c-60b6-47ec-ae63-fd5015cbf6f4)

 Restore code snippet: 
![image](https://github.com/openwallet-foundation/credo-ts/assets/61360727/1f82c1b1-b126-49d0-92ed-bc1eef55269d)

I am selecting  -wal  file by document picker and converting the content uri to relative path of the file.

![image](https://github.com/openwallet-foundation/credo-ts/assets/61360727/dd3bcaba-bb82-4c12-8cba-d40e1c2fe3d6)

When importing the wallet the encountered error is:
![image](https://github.com/openwallet-foundation/credo-ts/assets/61360727/7f7d531e-61e4-407e-8c35-d96ddc325d21)

How can I mitigate this error?

**Comment by genaris** [comment]
Apart from the `wal` and `shm` files, you should be seeing a file without suffix (i.e. `backup_wallet_arifshahriar028_1719384806907`). That's the one you should select. The three files must be present (toghether in the same directory) when importing, since all of them are needed to open the SQLite database.

**Comment by Arif-Shahriar028** [comment]
@genaris  I was also expecting a file without suffix. But there is no file generated like this.  But the older version of bifold generates only one file without suffix. Following is the generated files by the newer version of bifold:

![image](https://github.com/openwallet-foundation/credo-ts/assets/61360727/52d065dc-1b79-4b32-9fce-91bf374ec860)

**Comment by Arif-Shahriar028** [comment]
After `agent.wallet.export()`, I was using `RNFS.unlink(filePath)` which deleted the third file I was expecting. 

![image](https://github.com/openwallet-foundation/credo-ts/assets/61360727/52900acc-1a6f-431e-85e3-37eb229345f0)

After commenting out `RNFS.unlink()`, the exporting working fine. 

@genaris thanks for your idea!

**Comment by Arif-Shahriar028** [comment]
After `agent.wallet.export()`, I was using `RNFS.unlink(filePath)` which deleted the third file I was expecting.

![image](https://github.com/openwallet-foundation/credo-ts/assets/61360727/c995054c-6554-4a71-a1bd-66dea20bcd59)

After commenting out `RNFS.unlink()`, the exporting working fine.

@genaris thanks for your idea!
