### ISSUE TITLE
Credential security in a rooted android phone

### ISSUE THREAD

**Issue by Arif-Shahriar028** [openwallet-foundation/credo-ts#1987]
I have a few questions regarding the cryptographic key security in the Bifold wallet which is based on credo-ts:

1. How does the Bifold wallet / credo maintain the security of credentials? 
2. Is it possible to retrieve credentials from a rooted Android phone by accessing root files? If so, what are the potential risks and mitigations?
3. Is there any encryption decryption method to encrypt the credentials of a wallet? What is the responsibility of wallet key in this case?
4. Can we utilize hardware-specific security measures, such as a Hardware Security Module (HSM) or Yubico to enhance the security of cryptographic keys in the Bifold wallet/ credo?

I appreciate any insights or recommendations on these topics. Thank you.

**Comment by swcurran** [comment]
Probably more appropriate to ask in the Bifold repo — https://github.com/openwallet-foundation/bifold-wallet

**Comment by Arif-Shahriar028** [comment]
@swcurran thanks for your response! 

I have submitted another issue in the bifold repo and they have responded with some insights:

https://github.com/openwallet-foundation/bifold-wallet/issues/1226#issue-2446755553
