### ISSUE TITLE
Wallet cannot be imported due to missing config table

### ISSUE THREAD

**Issue by trta2352** [openwallet-foundation/credo-ts#1992]
In our project we have implement a wallet backup and restore functionality. 

Wallet is exported using: 

```
 async exportWallet(agent: Agent, passphrase: string, destination: string) {
    await agent.wallet.export({ key: passphrase, path: destination });
    return await RNFS.readFile(destination, 'base64');
 }
 
 Destination in this case is:
 RNFS.CachesDirectoryPath + '/backup/' + '' + walletId + '_' + 'backup.sqlite'
```
This file is then uploaded to our backend. 

When we restore the wallet, at this point the user either did a clean reinstall or we deleted the wallet using: 

`await RNFS.unlink(RNFS.DocumentDirectoryPath + '/.afj/')`

We then download the base64 string and create a file:
```
await RNFS.writeFile(path, downloadedWalletInBase64Format, 'base64');

Where path is:
RNFS.CachesDirectoryPath + '/backup/' + '' + walletId + '_' + 'backup.sqlite'
```

.sqllite is at this point successfully created so we import the wallet using: 

```
      const agent = await this.initializeAgent({
        code: passphrase,
        walletId,
      });
      await agent.wallet.delete();

      await agent.wallet.import(
        {
          id: walletId,
          key: passphrase,
        },
        { key: passphrase, path: destination },
      );
```

At this point we get the following error (on both iOS and Android):

**`[WalletError: Error importing wallet '56c444c4-29e6-4411-a30f-fa9c026223f2': Error fetching store configuration Caused by: error returned from database: (code: 1) no such table: config]`**

We are using the following versions:

```
    "@credo-ts/anoncreds": "^0.5.3",
    "@credo-ts/askar": "0.5.3",
    "@credo-ts/core": "0.5.3",
    "@credo-ts/indy-vdr": "^0.5.3",
    "@credo-ts/question-answer": "^0.5.3",
    "@credo-ts/react-hooks": "0.6.1",
    "@credo-ts/react-native": "0.5.3",
    "@hyperledger/anoncreds-react-native": "0.2.2",
    "@hyperledger/aries-askar-react-native": "0.2.1",
    "@hyperledger/indy-vdr-react-native": "^0.2.2",
```

**Comment by sairanjit** [comment]
@trta2352 While exporting wallet you have to export all 3 files:

<img width="180" alt="Screenshot 2024-08-07 at 10 14 07 PM" src="https://github.com/user-attachments/assets/2e8082fd-88f8-4c8c-9a6e-2f69950a83d1">

**Comment by icc-romeu** [comment]
@sairanjit thanks for the response but, what does the `await agent.wallet.export({ key: passphrase, path: destination });` export then? I was expecting this to export a **single** SQLite file you can store somewhere else. Otherwise, why not shut down the agent and copy the 3 files directly?  Isn't the export feature useless then?

In any case, are you suggesting we need to copy the exported file + existing WAL + existing shm?

**Comment by genaris** [comment]
> @sairanjit thanks for the response but, what does the `await agent.wallet.export({ key: passphrase, path: destination });` export then? I was expecting this to export a **single** SQLite file you can store somewhere else. Otherwise, why not shut down the agent and copy the 3 files directly? Isn't the export feature useless then?
> 
> In any case, are you suggesting we need to copy the exported file + existing WAL + existing shm?

Wallet Export feature makes a copy of wallet using specific encryption settings (e.g. the key can be different from the original one) without the need of shutting down the agent and doing the process manually. To do so, Credo relies on Askar's store `copy_to` feature.

The problem we identified is that most of the time this process generates three output files: the main sqlite file, a WAL file and a SCH file. This has to do with the way Askar manages the database (it uses [Write Ahead Logging](https://www.sqlite.org/wal.html) by default). The normal procedure would be these two files to be deleted, but it seems that Askar is not properly closing the the DB and therefore they remain there, making it mandatory to copy the three of them to do a succesfull backup.

I think this should be fixed somewhere in Askar, but maybe can also be worked-around in Credo (e.g. by asking it to not open the output DB in WAL mode). For the time being, the proper way of exporting a wallet is to call this `agent.wallet.export()` and making sure to include all generated `<output-filename.*>` files in the backup.

**Comment by icc-romeu** [comment]
Thanks @genaris for the long explanation, this is very useful indeed :) . I usually close the wallet before we do all the backup procedure, so I expected -as you said- that no WAL was needed, hence the confusion.

Thx

**Comment by trta2352** [comment]
@genaris So what we tried now is exporting the wallet in the following way:

```
  async exportWallet(agent: Agent, passphrase: string, destination: string) {
    await agent.wallet.export({ key: passphrase, path: destination });

    const sqliteDBSHm = '-shm';
    const sqliteDBWal = '-wal';
    // Export 3 database files: -shm, -wal and one without specific extension
    const exportSqliteDB = await RNFS.readFile(destination, 'base64').catch();
    const exportSqliteDBSHm = await RNFS.readFile(destination + sqliteDBSHm, 'base64').catch();
    const exportSqliteDBWal = await RNFS.readFile(destination + sqliteDBWal, 'base64').catch();

    if (!exportSqliteDB || !exportSqliteDBSHm || !exportSqliteDBWal) {
      logger.log('Wallet export failed', destination);
    }

    return (
      exportSqliteDB + BACKUP_FILE_DELIMITER + exportSqliteDBSHm + BACKUP_FILE_DELIMITER + exportSqliteDBWal
    );
  }
```
This works fine. Then we download the string, create the folder and create the files in it:

 ```
 const path = RNFS.CachesDirectoryPath + '/backup/' + walletId + '/';
// one string consisting of the 3 files converted to base64 with a . separator
const walletData = wallet.split(BACKUP_FILE_DELIMITER);
const sqliteDB = 'sqlite.db';
const sqliteDBSHm = 'sqlite.db-shm';
const sqliteDBWal = 'sqlite.db-wal';

if (walletData.length === 3) {
        await RNFS.writeFile(path + sqliteDB, walletData[0], 'base64');
        await RNFS.writeFile(path + sqliteDBSHm, walletData[1], 'base64');
        await RNFS.writeFile(path + sqliteDBWal, walletData[2], 'base64');

        await AgentService.shared.importWallet(walletId, walletPassword, path + sqliteDB);
}
```

All 3 files are successfully created at this point. 

What path are we supposed to add pass to import the wallet?
If we pass just path (path to the folder where the 3 files are located): 
`  await AgentService.shared.importWallet(walletId, walletPassword, path);
`
**We get the "The requested database path was not found" error.** 

If we pass the path to the main file 
`  await AgentService.shared.importWallet(walletId, walletPassword, path + sqliteDB);
`
**Import does not fail with any error but no credentials are present in the wallet.**

**Comment by trta2352** [comment]
Update: Import failure was caused by an incorrect wallet export. 

When exporting the wallet it is required to add the path to the main sqlite file. Example: ` await agent.wallet.export({ key: passphrase, path: destination + '/sqlite.db' });`

Then in the import add the path to the "main" sqlite (while also creating the -shm and -wal files in the same folder) file, not to the enclosing folder. Example: 
`await AgentService.shared.importWallet(walletId, walletPassword, path + sqliteDB);`
