### ISSUE TITLE
Bug: Error initializing Agent

### ISSUE THREAD

**Issue by MosCD3** [openwallet-foundation/credo-ts#2032]
Came across this while configuring and initializing the Agent 
`Error creating key with key type 'ed25519': Cannot read property 'Software' of undefined`

Tracing down the stack trace to
```
async getMediationConnection(mediatorInvitationUrl) -> 
    this.mediationRecipient.getRouting({ useDefaultMediator: false });
     const recipientKey = await agentContext.wallet.createKey({ keyType: crypto_1.KeyType.Ed25519 });
```
     
In previos versions of credo its working fine, but after upgrading to 0.5.9, we have this error

**Comment by TimoGlastra** [comment]
I think you need to update your version of Aries Askar

**Comment by MosCD3** [comment]
@TimoGlastra You are totally right, after updating ask version, it worked 
Thank you
