### ISSUE TITLE
0.5.12 release cannot be installed

### ISSUE THREAD

**Issue by dbluhm** [openwallet-foundation/credo-ts#2086]
I'm trying to install credo 0.5.12 using npm and am running into the following error:

```
npm error code EUNSUPPORTEDPROTOCOL
npm error Unsupported URL Type "link:": link:/Users/martinauer/Documents/credo-ts/packages/core
```

This seems to be the result of a bad dependency in the @protokoll/core package at version 0.2.27. This is fixed in the next release, 0.2.28. But the version constraints in credo do not permit me to override the package getting installed with Credo 0.5.12.

Unless there's a workaround I'm not aware of, this is preventing me from using the 0.5.12 release.

**Comment by TimoGlastra** [comment]
Can you try with the latest alpha? 

We'll probably make a 0.5.13 release soon as there's been quite some people with issues.

**Comment by dbluhm** [comment]
0.5.13-alpha-20241107100446 installs as expected without errors

**Comment by TimoGlastra** [comment]
Okay triggered a release for 0.5.13! :)

https://github.com/openwallet-foundation/credo-ts/releases/tag/v0.5.13
