### ISSUE TITLE
bug: anoncreds-rs issuance of revocation index 0 silently issues non-revokable cred

### ISSUE THREAD

**Issue by gmulhearn** [openwallet-foundation/credo-ts#2125]
I was finding that when i issued a revocable cred with index 0, the issued credential would be issued without any attachment to a revocation registry (non-revocable). e.g.:
```ts
  const credEx = await credentials.offerCredential({
    protocolVersion: "v2",
    connectionId: connId,
    credentialFormats: {
      anoncreds: {
        credentialDefinitionId: credDefId,
        attributes: [
          { name: "name", value: "Jane Doe" },
          { name: "age", value: "23" },
        ],
        revocationRegistryIndex: 0,
        revocationRegistryDefinitionId: revRegDefId,
      },
    },
  });
```

I believe this is because the anoncreds-rs issuer service only assembles `CredentialRevocationConfig` if `revocationRegistryIndex` is truthy - so it skips `CredentialRevocationConfig` construction if `revocationRegistryIndex` is `0`. Problem resolved when i moved to index `1`

https://github.com/openwallet-foundation/credo-ts/blob/9d934afc87eb7dad87fd65681ada4df0333bd439/packages/anoncreds/src/anoncreds-rs/AnonCredsRsIssuerService.ts#L323

**Comment by gmulhearn** [comment]
related, and possibly indicates the problem exists in other places: https://github.com/openwallet-foundation/credo-ts/pull/2008

**Comment by TimoGlastra** [comment]
Thanks for this, i think we need to check for undefined instead. Are you willing to make a PR?
