### ISSUE TITLE
Question: Ethereum support

### ISSUE THREAD

**Issue by icc-romeu** [openwallet-foundation/credo-ts#2132]
Hi,

I was looking at the code and found some references to ethereumAddresses. But in this issue -https://github.com/openwallet-foundation/credo-ts/issues/132- I see that Timo comments that there is no support of ethereum as blockchain.

I assume the ethereum references I found are only there for verification purposes, isn't it? https://github.com/openwallet-foundation/credo-ts/blob/07a60cd3028665b6a348be6bac1b3cc8a30e4110/packages/core/src/modules/dids/domain/verificationMethod/VerificationMethod.ts#L16

**Comment by TimoGlastra** [comment]
Hi @icc-romeu.

Ethereum is not supported at the moment. These fields were added based on definitions in specifications. 

However it should be quite easy to create a did resolver / registrar for ethereum using the inferfaces
