### ISSUE TITLE
Generating a nonce for a proof request

### ISSUE THREAD

**Issue by berendsliedrecht** [openwallet-foundation/credo-ts#646]
Right now, It not really possible to generate a nonce, via `proofService.generateNonceForProofRequest()` without a lot of hassle because you need to instantiate the `proofService`. 

We should add a way to generate this nonce without instantiating this whole class, or we should create it for the user if nothing is provided in the `options` of the constructor for the `proofRequest` class.

**Comment by TimoGlastra** [comment]
Too much as changed, not really relevant anymore
