### ISSUE TITLE
Got error after accepting connectionless credential offer from trinsic

### ISSUE THREAD

**Issue by standlove** [openwallet-foundation/credo-ts#694]
Hi,

After accepting the connectionless credential offer from trinsic, we are getting this error:
```
 "error": {
    "name": "AriesFrameworkError",

    "message": "Cannot verify service without senderKey on incoming message (received AnonCrypt or unpacked message)",
```

We are using v0.1.0, is it a bug in ariesframework?  

Thanks.

**Comment by swcurran** [comment]
I'm not sure about this.  Tagging @tmarkovski and @andrewwhitehead to see if they can provide any insight. Tomislav/Andrew -- feel free to ask any questions needed to understand the scenario.

**Comment by TimoGlastra** [comment]
Trinsic has been deprecated
