### ISSUE TITLE
Persistent message repositories for Pickup Protocol

### ISSUE THREAD

**Issue by genaris** [openwallet-foundation/credo-ts#741]
Currently, Agent uses by default an in-memory message queue for outbound messages when a session with the receiver is not established, using an `InMemoryMessageRepository` instance as message repository used by `MessageSender`and `MessagePickupService`.

For server-side scenarios (i.e. mediators or agents dealing with other agents without endpoints) is important to use a persistent message queue, so it can be retrieved when agent is restarted.

Last modifications introduced in #690 allow to pass an injection container to `Agent` constructor, meaning that it is possible to register a different object implementing `MessageRepository` interface, so it could be just a matter of documenting it and improving the interface to match use cases more complex than the in-memory one.

**Comment by TimoGlastra** [comment]
Do you think it would be convenient to add something like a persistent state interface that could be leveraged by different parts of the framework? I think this could be useful more broadly for things like:
 - the message repository
 - inbound message queue
 - outbound message queue

**Comment by TimoGlastra** [comment]
Lots of improvments to message repository have been made. I think we can close this
