### ISSUE TITLE
Return InboundMessageContext from MessageReceiver.receiveMessage

### ISSUE THREAD

**Issue by cvarjao** [openwallet-foundation/credo-ts#762]
In order to process connection-less proof request and wait for the underline message to be processed, it would be helpful if
[MessageReceiver.receiveMessage](https://github.com/hyperledger/aries-framework-javascript/blob/245223acbc6f50de418b310025665e5c1316f1af/packages/core/src/agent/MessageReceiver.ts#L68) returns the underline `InboundMessageContext`.

Notice that [Agent.receiveMessage](https://github.com/hyperledger/aries-framework-javascript/blob/245223acbc6f50de418b310025665e5c1316f1af/packages/core/src/agent/Agent.ts#L256) already has a return statement, but right now its `void` as that is the output of `MessageReceiver.receiveMessage`

**Comment by TimoGlastra** [comment]
Hi @cvarjao! Just trying to understand what you'd like to achieve. Which parameter in the inbound message context is it that you need? Or is it just having the inbound message context as a whole?

**Comment by cvarjao** [comment]
@TimoGlastra, I think we got this figured out, but interested in your feedback.

We needed a way to identifies notifications that are coming from a QR code that has just been scanned.
The workflow is that whenever the user scans a QR Code, the wallet wait for either a Credential Offer or a Proof Request from that "connection". And I am using connection loosely as it could be a connection-less proof request.

Here are the bits that extracts the `connection Id`, and the `message thread id` (for connection-less):
https://github.com/hyperledger/aries-mobile-agent-react-native/blob/276bd7178788960392576fa9ec7ec4353526ff1c/core/App/screens/Scan.tsx#L29
https://github.com/hyperledger/aries-mobile-agent-react-native/blob/276bd7178788960392576fa9ec7ec4353526ff1c/core/App/screens/Scan.tsx#L54

and here is where we wait for a notification from that connection Id or Thread Id:
https://github.com/hyperledger/aries-mobile-agent-react-native/blob/276bd7178788960392576fa9ec7ec4353526ff1c/core/App/screens/Connection.tsx#L120

I am not sure if the message thread Id  is the best metadata to use, and I was wondering if there was any other metadata that could provide an accurate way to provide a relationship between the scanned QR Code (specifically connection-less proof request), and the underline proof request entry parsed/created by AFJ as a result of scanning a QR Code.

**Comment by TimoGlastra** [comment]
receiveMessage has been deprected. We now handle all out of band messages using the OOB API
