### ISSUE TITLE
Allow invitations to use public DID

### ISSUE THREAD

**Issue by TimoGlastra** [openwallet-foundation/credo-ts#84]
Currently the framework only supports invitations that directly include the `serviceEndpoint`, `recipientKeys` and `routingKeys`. However the connection protocol RFC states that an invitation can use use a publicly resolvable DID. With the new ledger service from #82 we can now resolve public Indy / Sov DIDs.

Indy doesn't support DID docs yet, but we can retrieve the service information using an ATTRIB request I think? This information can be used to respond to the invitation.

### Checklist
- [x] Check if received invitation contains DID. Retrieve required data from ledger if present and then use that going forward.
- [x] Allow to create an invitation with a DID instead of the separate attributes.
- [x] Only use the public did for the invitation, for the other messages a peer did should still be used
- [x] We need to store somewhere a public DID was used for the invitation. ACA-Py has a key in the record, should we also use this approach?

### Questions
- When creating an invitation with DID, should it just be a string parameter, or should we only allow to create invitation with the current agent public DID?
- Are there other places in the framework where public DIDs can be used per the RFCs?
    - Not implemented yet, but [Out-Of-Band Protocol](https://github.com/hyperledger/aries-rfcs/blob/master/features/0434-outofband/README.md) can use public DIDs

**Comment by nodlesh** [comment]
Is there any plans to implement did exchange invitations with public DIDs? I see in issue #992 that there was work started on it as one point with no closure.

**Comment by TimoGlastra** [comment]
Yes i think documentation is the most important, and maybe adding some utils to make dids DIDComm-ready

One thing that is missing (i think?) is whether a did is rotated? I'm not 100%. Like if you want to use a did:web for invitation and then keep using that for the connection instead of a did:peer

**Comment by nodlesh** [comment]
Thanks for the clarifications here. So I went ahead and implemented invitations with public dids in my credo agent, however I always get an error stating `Unable to resolve did document for did`.  Here is what I'm doing, 
When the agent is instructed to use a public did we do a oob.createInvitation. 
In there we get the public did of the agent with this, 
```
    const publicDidInfoRecord = await this.agent.genericRecords.findById('PUBLIC_DID_INFO')
    const content = publicDidInfoRecord.content as { didInfo: { did: string } }
    return content.didInfo.did
```

I put that did in the invitation options as invitationDid and try to create the invitation. 

This is the full error I get. 
```
error: {
    name: 'CredoError',
    message: "Unable to resolve did document for did '8yLAa5ZTNTxC4rkkgLMpq6': invalidDid undefined",
    status: 500,
    errors: [],
    stack: "CredoError: Unable to resolve did document for did '8yLAa5ZTNTxC4rkkgLMpq6': invalidDid undefined\n" +
      '    at DidResolverService.resolveDidDocument (/aries-backchannels/credo-ts/server/node_modules/@credo-ts/core/src/modules/dids/services/DidResolverService.ts:159:13)\n' +
      '    at async DidCommDocumentService.resolveServicesFromDid (/aries-backchannels/credo-ts/server/node_modules/@credo-ts/core/src/modules/didcomm/services/DidCommDocumentService.ts:21:25)\n' +
      '    at async OutOfBandApi.resolveInvitationRecipientKeyFingerprints (/aries-backchannels/credo-ts/server/node_modules/@credo-ts/core/src/modules/oob/OutOfBandApi.ts:951:41)\n' +
      '    at async OutOfBandApi.createInvitation (/aries-backchannels/credo-ts/server/node_modules/@credo-ts/core/src/modules/oob/OutOfBandApi.ts:233:38)'
```

Any idea what I'm doing wrong here? As I'm writing this I'm wondering if it should be a qualified did...

**Comment by swcurran** [comment]
I don’t know the details, but we shouldn’t be creating anything new with unqualified DIDs.  I think your are trying to create a DIDComm connection, and if so, you should probably be using a `did:peer:4` DID.

**Comment by nodlesh** [comment]
Actually I would expect the credo call for the publicDidInfoRecord to be returning a qualified did to me.

**Comment by genaris** [comment]
We don't have a 'Public DID' built-in configuration in Credo, so I guess you are following the strategy in AATH to save and retrieve the DID we want to use from a generic record.

in [AATH code] I see that it is saving public DID using unqualified Indy format (since it calls [`indyDidFromPublicKeyBase58`](https://github.com/openwallet-foundation/credo-ts/blob/9d934afc87eb7dad87fd65681ada4df0333bd439/packages/core/src/utils/did.ts#L4)), so @swcurran comment is relevant here, as the agent will not be able to resolve it. However, there is nothing wrong in creating an invitation using a non-peer DID, so I think it should work if you pass it to `createInvitation` in the format `did:indy:{namespace}:{identifier}`
