### ISSUE TITLE
add agent middleware

### ISSUE THREAD

**Issue by TimoGlastra** [openwallet-foundation/credo-ts#97]
As a developer I sometimes want to apply custom logic for all incoming messages. We already have handlers that allow to implement logic for a custom message type. I think it would be beneficial to introduce the concept of middleware into aries-framework-javascript.

aries-framework-dotnet also implements the concept of middleware which we can take as [an example](https://github.com/hyperledger/aries-framework-dotnet/blob/fb5d3081f2740c9b02e7bfbc82a9c61f6de4a936/src/Hyperledger.Aries/Agents/Abstractions/IAgentMiddleware.cs)

### Checklist

- [ ] create `AgentMiddleware` interface
- [ ] call middleware before/after passing to handler (see question below)
    - I think `Dispatcher` would be the best place to call middleware
- [ ] add function to register middleware to `Agent` (like`registerHandlers`)
    - one function to register them all, or function that can be called multiple times?

### Questions

- When should middleware be called?
    - Before passing to handler / after passing to handler / both?
    - .NET runs the middleware after passing a message to the handler. 

### Use cases

Probably a lot more, but this are two I can think of at the moment.

- [#96: Check connection acknowledgement for all messages, not just trust ping and ack](https://github.com/hyperledger/aries-framework-javascript/issues/96)
- [Message Tracing](https://github.com/hyperledger/aries-rfcs/blob/master/features/0034-message-tracing/README.md)

**Comment by jadhavajay** [comment]
This would be nice enhancement @TimoGlastra .
However, in my opinion, the AFJ should only define the `AgentMiddleware` abstraction / interfaces, and NOT the concrete implementations of the Middleware. Those are normally provided in the Node.js Web framework-level like Express, Oak, etc.

AF .NET also does the same way I described.
For example the interface is defined here in the Framework abstraction: 
-  [IAgentMiddleware](https://github.com/hyperledger/aries-framework-dotnet/blob/02617cfa24c796eedfdb9549f9200a92a714e1a2/src/Hyperledger.Aries/Agents/Abstractions/IAgentMiddleware.cs)

.. and the implementation is in 

- [PaymentsAgentMiddleware.cs](https://github.com/hyperledger/aries-framework-dotnet/blob/02617cfa24c796eedfdb9549f9200a92a714e1a2/src/Hyperledger.Aries.Payments.SovrinToken/PaymentsAgentMiddleware.cs)

 Happy to discuss if there are other ideas.

**Comment by gnarula** [comment]
I'd suggest having the middleware execute both, before the call to the handler and after the result of the handler is handled (i.e. outgoing message is sent).

The latter would specially be useful for scenarios where we need to be certain that the other party has received the message.
Example: In ConnectionService, we mark the state as `COMPLETE` before the ack message is sent. Ideally we'd want that to be done after the message is send successfully.

**Comment by jadhavajay** [comment]
We discussed & agreed in today's meeting that the middleware implementation will be runtime-agnostic. So that it may be consumed in Node.js Express, Deno or React-Native.
