### ISSUE TITLE
Getting issue related to indy-sdk while doing npm/yarn install in windows

### ISSUE THREAD

**Issue by dineshnextbrain** [openwallet-foundation/credo-ts#987]
![image](https://user-images.githubusercontent.com/111457365/185937165-f8810808-76ca-4017-aa10-7464f4ccfb23.png)

**Comment by blu3beri** [comment]
Hi, 

1. Do you have a full stack-trace available?
2. Did you install the indy-sdk according to the guides? (https://aries.js.org/guides/getting-started/installation/nodejs/windows)

**Comment by dineshnextbrain** [comment]
![image](https://user-images.githubusercontent.com/111457365/187666318-14ee6b75-7742-46ef-b2b9-f3901c5015f1.png)

facing issue with indy-sdk in windows

**Comment by TimoGlastra** [comment]
Did you manage to solve the issue @dineshnextbrain?

**Comment by TimoGlastra** [comment]
Indy SDK has been removed
