### ISSUE TITLE
Support receiving out of band invitations with public dids for the didexchange protocol

### ISSUE THREAD

**Issue by TimoGlastra** [openwallet-foundation/credo-ts#992]
#930 adds support for receiving out of band invitations with public dids, but only supports processing it for 0160 connections. We should still add support to do this with the didexchange protocol

**Comment by TimoGlastra** [comment]
That's an interesting way to get the credential you need! 

I think yes, currently the flow doesn't take into account the implicit flow. What would be the easiest approach I think is to keep the `DidExchangeProtocol.createRequest` to need a out of band record, that we can create on the module layer beforehand. Another approach would be to create a `DidExchangeProtocol.createRequestFromDid` and `ConnectionService.createRequestFromDid` and expose it through a `ConnectionsApi.sendRequestToDid` or something similar (don't like sendRequestToDid too much).

I think it would work fine with the pthid:
> When a request responds to an implicit invitation, its ~thread.pthid MUST contain a [DID URL](https://w3c-ccg.github.io/did-spec/#dfn-did-url) that resolves to the specific service on a DID document that contains the invitation.

We should modify the request to include the public did with service as the pthid, like so: https://github.com/hyperledger/aries-rfcs/blob/main/features/0023-did-exchange/README.md#example-referencing-an-implicit-invitation

The connectionless flow should also work I assume and is probably easier to implement, so I think it's a bit dependant on which flow works best for your use case. At the moment we don't support proposals for connectionless credential issuance though

**Comment by genaris** [comment]
Thanks for the explanation and suggestions @TimoGlastra ! I think it would be nice to support these implicit invitations from the module level in order to make it more evident for users how to handle both invitation types. I'll dig a bit more about the possibilities and open a PR including these public DID handling in DIDExchange protocol.

**Comment by TimoGlastra** [comment]
@genaris are you still working on this?

**Comment by genaris** [comment]
Slowly but yes!

**Comment by genaris** [comment]
I think https://github.com/openwallet-foundation/credo-ts/pull/1348, combined with the support of resolvable DIDs in DID Exchange in https://github.com/openwallet-foundation/credo-ts/pull/1550 covered this, unless I'm missing something.
